### ISSUE TITLE
Browser Error

### ISSUE THREAD

**Issue by bothaxsploit** [MattMoony/d4v1d#2]
Hey im getting the error "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." everytime i try to execute the command br or browser. Btw what are the options i can use? there arent any options to use at the help menu :(

**Comment by DerLomo** [comment]
> 
> 
> Hey im getting the error "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." everytime i try to execute the command br or browser. Btw what are the options i can use? there arent any options to use at the help menu :(

Please If you found the way to fix this or find other project that actually work let me know

**Comment by MattMoony** [comment]
Hey, sorry for the late reply!

This isn't really a bug - well, okay, it kinda is ... ^^ - anyway, this should only happen, when you haven't grabbed anything yet ...
So, use the CLI to get some info about a user and try again. E.g.:

```bash
login
get o matt_moony
browse
```

**Keep in mind though** that the frontend isn't the most extensive anyways... It's a way to look at somewhat fancy network graphs of who users follow / are followed by, but not too much more than that.

Furthermore, I know that the command line is bit weird to use - especially, since I haven't written too much documentation for it ... ^^ - just use `?` or `help` wherever you need it. E.g.:

```bash
get ?
```

![image](https://user-images.githubusercontent.com/41878842/116775685-977dfd00-aa64-11eb-9ab8-64cc0f3f042c.png)

In general, the CLI should be rather nice and always tell you what option / argument you're missing. E.g.:

```bash
get o
```

![image](https://user-images.githubusercontent.com/41878842/116775707-b67c8f00-aa64-11eb-8429-ad5c6d260160.png)

_Hope this helps!_
_- Matthias_
